// сортировка
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_FILTRATION_ALL = 'SET_FILTRATION_ALL';
export const SET_FILTRATION_WITHOUT = 'SET_FILTRATION_WITHOUT';
export const SET_FILTRATION_ONE_TRANSFER = 'SET_FILTRATION_ONE_TRANSFER';
export const SET_FILTRATION_TWO_TRANSFER = 'SET_FILTRATION_TWO_TRANSFER';
export const SET_FILTRATION_THREE_TRANSFER = 'SET_FILTRATION_THREE_TRANSFER';
export const SET_FILTRATION_NOT_ALL = 'SET_FILTRATION_NOT_ALL';

